# Generated by Django 4.1.7 on 2023-03-18 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iol', '0005_alter_signals_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='iolist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iolist',
            name='created_by',
            field=models.CharField(default='Pravin', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iolist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='created_by',
            field=models.CharField(default='Pravin', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.CharField(default='Pravin', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='signals',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signals',
            name='created_by',
            field=models.CharField(default='Pravin', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signals',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
