# Generated by Django 4.1.7 on 2025-04-02 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created_by', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment', models.CharField(blank=True, choices=[('Carton/Tote Handling', 'Carton/Tote Handling'), ('Slit Roll', 'Slit Roll'), ('CBS', 'CBS'), ('Robotics', 'Robotics'), ('ASRS-MB', 'ASRS-MB'), ('ASRS-Stacker', 'ASRS-Stacker')], default='Carton/Tote Handling', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('segment', models.CharField(blank=True, choices=[('Carton/Tote Handling', 'Carton/Tote Handling'), ('Slit Roll', 'Slit Roll'), ('CBS', 'CBS'), ('Robotics', 'Robotics'), ('ASRS-MB', 'ASRS-MB'), ('ASRS-Stacker', 'ASRS-Stacker')], default='Carton/Tote Handling', max_length=50)),
                ('created_by', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('is_Murr', models.BooleanField(default=False)),
                ('isFreeze', models.BooleanField(default=False)),
                ('PLC', models.CharField(choices=[('Siemens', 'Siemens'), ('Allen Bradley', 'Allen Bradley'), ('Mitsubishi', 'Mitsubishi')], default='Siemens', max_length=50)),
                ('panels', models.JSONField(blank=True, null=True)),
                ('panel_numbers', models.CharField(blank=True, max_length=1000, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('exported_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_code', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=40)),
                ('component_description', models.TextField(blank=True, max_length=100)),
                ('function_purpose', models.TextField(blank=True, max_length=100)),
                ('device_type', models.TextField(blank=True, max_length=100)),
                ('signal_type', models.CharField(choices=[('DI', 'DI'), ('DO', 'DO'), ('Encoder', 'Encoder')], default='DI', max_length=10)),
                ('remarks', models.TextField(blank=True, max_length=100)),
                ('segment', models.CharField(blank=True, choices=[('Carton/Tote Handling', 'Carton/Tote Handling'), ('Slit Roll', 'Slit Roll'), ('CBS', 'CBS'), ('Robotics', 'Robotics'), ('ASRS-MB', 'ASRS-MB'), ('ASRS-Stacker', 'ASRS-Stacker')], default='Carton/Tote Handling', max_length=50)),
                ('initial_state', models.BooleanField(default=True)),
                ('location', models.CharField(choices=[('FD', 'FD'), ('CP', 'CP')], max_length=2)),
                ('created_by', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Demo_3d_Property', models.CharField(blank=True, max_length=200, null=True)),
                ('module', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='iol.module')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('segment', models.CharField(blank=True, choices=[('Carton/Tote Handling', 'Carton/Tote Handling'), ('Slit Roll', 'Slit Roll'), ('CBS', 'CBS'), ('Robotics', 'Robotics'), ('ASRS-MB', 'ASRS-MB'), ('ASRS-Stacker', 'ASRS-Stacker')], default='Carton/Tote Handling', max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iol.project')),
            ],
        ),
        migrations.CreateModel(
            name='IOList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('equipment_code', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=40)),
                ('tag', models.CharField(max_length=100)),
                ('signal_type', models.CharField(max_length=10)),
                ('device_type', models.TextField(blank=True, max_length=100)),
                ('actual_description', models.TextField(max_length=200)),
                ('panel_number', models.CharField(blank=True, default='CP01', max_length=10, null=True)),
                ('node', models.CharField(blank=True, max_length=10, null=True)),
                ('rack', models.IntegerField(blank=True, null=True)),
                ('module_position', models.IntegerField(blank=True, null=True)),
                ('terminal_block', models.CharField(blank=True, max_length=5, null=True)),
                ('terminal_number', models.IntegerField(blank=True, null=True)),
                ('channel', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(choices=[('FD', 'FD'), ('CP', 'CP')], default='CP', max_length=2)),
                ('io_address', models.CharField(blank=True, max_length=20, null=True)),
                ('Cluster', models.CharField(default='Testing', max_length=50)),
                ('created_by', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(null=True)),
                ('cluster_number', models.PositiveIntegerField(null=True)),
                ('iomodule_name', models.CharField(blank=True, max_length=10, null=True)),
                ('Demo_3d_Property', models.CharField(blank=True, max_length=200, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iol.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
