# Generated by Django 4.1.7 on 2023-03-13 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Signals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_code', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=40)),
                ('component_description', models.TextField(blank=True, max_length=100)),
                ('function_purpose', models.TextField(blank=True, max_length=100)),
                ('device_type', models.TextField(blank=True, max_length=100)),
                ('signal_type', models.CharField(choices=[('DI', 'DI'), ('DO', 'DO'), ('Encoder', 'Encoder')], default='DI', max_length=10)),
                ('remarks', models.TextField(blank=True, max_length=100)),
                ('segment', models.CharField(blank=True, max_length=50)),
                ('initial_state', models.BooleanField(default=True)),
                ('location', models.CharField(choices=[('FD', 'FD'), ('CP', 'CP')], max_length=2)),
                ('module', models.ManyToManyField(to='iol.module', verbose_name='modules')),
            ],
        ),
        migrations.CreateModel(
            name='IOList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('equipment_code', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=40)),
                ('tag', models.CharField(editable=False, max_length=100)),
                ('signal_type', models.CharField(max_length=10)),
                ('actual_description', models.TextField(max_length=100)),
                ('panel_number', models.CharField(max_length=10)),
                ('node', models.CharField(max_length=10)),
                ('rack', models.IntegerField(blank=True, null=True)),
                ('module_position', models.IntegerField(blank=True, null=True)),
                ('terminal_block', models.CharField(blank=True, max_length=5, null=True)),
                ('terminal_number', models.IntegerField(blank=True, null=True)),
                ('channel', models.IntegerField()),
                ('io_address', models.CharField(max_length=10)),
                ('modules', models.ManyToManyField(to='iol.module', verbose_name='modules')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iol.project')),
            ],
        ),
    ]
