# Generated by Django 4.1.7 on 2023-03-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iolist',
            name='channel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iolist',
            name='io_address',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='iolist',
            name='node',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='iolist',
            name='panel_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
