# Generated by Django 4.1.7 on 2023-03-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iolist',
            name='device_type',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
