# Generated by Django 4.1.7 on 2023-03-15 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iol', '0002_alter_iolist_channel_alter_iolist_io_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signals',
            name='module',
        ),
        migrations.CreateModel(
            name='Signals_Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iol.module')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iol.signals')),
            ],
        ),
        migrations.AddField(
            model_name='signals',
            name='modules',
            field=models.ManyToManyField(through='iol.Signals_Module', to='iol.module', verbose_name='modules'),
        ),
    ]
