# Generated by Django 4.1.7 on 2023-03-16 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iol', '0002_iolist_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iolist',
            name='module',
            field=models.CharField(default='Testing', max_length=50),
        ),
        migrations.AlterField(
            model_name='signals',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='iol.module'),
        ),
    ]
