# Generated by Django 4.1.7 on 2023-03-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iol', '0003_alter_iolist_module_alter_signals_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='iolist',
            name='location',
            field=models.CharField(choices=[('FD', 'FD'), ('CP', 'CP')], default='CP', max_length=2),
        ),
        migrations.AlterField(
            model_name='iolist',
            name='panel_number',
            field=models.CharField(blank=True, default='CP01', max_length=10, null=True),
        ),
    ]
