# Generated by Django 4.1.7 on 2023-03-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iol', '0003_remove_signals_module_signals_module_signals_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signals',
            name='modules',
        ),
        migrations.AddField(
            model_name='signals',
            name='module',
            field=models.ManyToManyField(to='iol.module', verbose_name='modules'),
        ),
        migrations.DeleteModel(
            name='Signals_Module',
        ),
    ]
