# Generated by Django 4.1.7 on 2023-03-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iol', '0004_iolist_location_alter_iolist_panel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signals',
            name='segment',
            field=models.CharField(blank=True, choices=[('Carton/Tote Handling', 'Slit Roll'), ('Carton/Tote Handling', 'Slit Roll')], max_length=50),
        ),
    ]
